name: dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-push:
    name: docker-push
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == 'omaha-js/omaha' }}
    concurrency: ${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Initialize cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: baileyherbert/omaha

      - name: Docker authentication
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: TAG=${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
