name: dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-push:
    name: docker-push
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == 'omaha-js/omaha' }}
    concurrency: ${{ github.ref }}
    steps:
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: baileyherbert/omaha

      - name: Docker authentication
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to hub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: TAG=${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=baileyherbert/omaha:main
          cache-to: type=inline
